import type { Perk, PlayerStats } from '@/types/game';

/**
 * MEGA Perk Pool - Additional 20+ perks for maximum variety
 */

export const MEGA_PERKS: Perk[] = [
  // === COMMON PERKS ===
  {
    id: 'armor_boost',
    name: 'Iron Skin',
    description: 'Reduce damage taken by 15%',
    rarity: 'common',
    type: 'statBoost',
    tags: ['defense', 'survival'],
    apply: (stats: PlayerStats): PlayerStats => stats,
  },
  {
    id: 'sprint',
    name: 'Sprint',
    description: 'Increase movement speed by 20%',
    rarity: 'common',
    type: 'statBoost',
    tags: ['movement', 'speed'],
    apply: (stats: PlayerStats): PlayerStats => ({
      ...stats,
      baseMoveSpeed: stats.baseMoveSpeed * 1.2,
    }),
  },
  {
    id: 'steady_aim',
    name: 'Steady Aim',
    description: 'Increase critical hit damage by 50%',
    rarity: 'common',
    type: 'statBoost',
    tags: ['damage', 'crit'],
    apply: (stats: PlayerStats): PlayerStats => stats,
  },
  {
    id: 'scavenger',
    name: 'Scavenger',
    description: 'Increase pickup radius by 40%',
    rarity: 'common',
    type: 'statBoost',
    tags: ['utility'],
    apply: (stats: PlayerStats): PlayerStats => ({
      ...stats,
      pickupRadius: stats.pickupRadius * 1.4,
    }),
  },
  {
    id: 'second_wind',
    name: 'Second Wind',
    description: 'Restore 5 HP when reaching 25% health',
    rarity: 'common',
    type: 'behaviorMod',
    tags: ['health', 'survival'],
    apply: (stats: PlayerStats): PlayerStats => stats,
  },

  // === RARE PERKS ===
  {
    id: 'frost_arrows',
    name: 'Frost Arrows',
    description: 'Projectiles slow enemies by 30% for 2s',
    rarity: 'rare',
    type: 'weaponAugment',
    tags: ['projectile', 'crowd_control'],
    apply: (stats: PlayerStats): PlayerStats => stats,
  },
  {
    id: 'fire_trail',
    name: 'Blazing Trail',
    description: 'Leave a damaging fire trail while moving',
    rarity: 'rare',
    type: 'behaviorMod',
    tags: ['aoe', 'damage'],
    apply: (stats: PlayerStats): PlayerStats => stats,
  },
  {
    id: 'double_damage',
    name: 'Power Surge',
    description: 'Double damage on next 3 shots after kill',
    rarity: 'rare',
    type: 'behaviorMod',
    tags: ['damage', 'burst'],
    apply: (stats: PlayerStats): PlayerStats => stats,
  },
  {
    id: 'lightning_chain',
    name: 'Arc Lightning',
    description: 'Projectiles chain to 2 nearby enemies',
    rarity: 'rare',
    type: 'weaponAugment',
    tags: ['projectile', 'chain'],
    apply: (stats: PlayerStats): PlayerStats => ({
      ...stats,
      damage: stats.damage * 0.85,
    }),
  },
  {
    id: 'ghost_walk',
    name: 'Phase Shift',
    description: '20% chance to phase through projectiles',
    rarity: 'rare',
    type: 'behaviorMod',
    tags: ['survival', 'dodge'],
    apply: (stats: PlayerStats): PlayerStats => stats,
  },
  {
    id: 'rage_mode',
    name: 'Berserker Soul',
    description: 'Attack speed increases by 5% per kill (max 100%)',
    rarity: 'rare',
    type: 'behaviorMod',
    tags: ['attack', 'scaling'],
    apply: (stats: PlayerStats): PlayerStats => stats,
  },
  {
    id: 'reflect_damage',
    name: 'Thorns',
    description: 'Reflect 25% of damage taken back to attackers',
    rarity: 'rare',
    type: 'behaviorMod',
    tags: ['defense', 'damage'],
    apply: (stats: PlayerStats): PlayerStats => stats,
  },

  // === EPIC PERKS ===
  {
    id: 'meteor_strike',
    name: 'Meteor Storm',
    description: 'Summon meteor every 20s dealing massive AOE damage',
    rarity: 'epic',
    type: 'weaponAugment',
    tags: ['aoe', 'special'],
    apply: (stats: PlayerStats): PlayerStats => stats,
  },
  {
    id: 'assassin_strike',
    name: 'Assassin Strike',
    description: 'Teleport behind nearest enemy every 5s',
    rarity: 'epic',
    type: 'behaviorMod',
    tags: ['mobility', 'special'],
    apply: (stats: PlayerStats): PlayerStats => stats,
  },
  {
    id: 'shadow_clone',
    name: 'Shadow Clone',
    description: 'Create a clone that copies your attacks',
    rarity: 'epic',
    type: 'behaviorMod',
    tags: ['summon', 'damage'],
    apply: (stats: PlayerStats): PlayerStats => stats,
  },
  {
    id: 'laser_beam',
    name: 'Plasma Cannon',
    description: 'Fire devastating laser beam every 15s',
    rarity: 'epic',
    type: 'weaponAugment',
    tags: ['special', 'damage'],
    apply: (stats: PlayerStats): PlayerStats => stats,
  },
  {
    id: 'blood_rage',
    name: 'Crimson Fury',
    description: 'Gain 2% all stats per kill (permanent)',
    rarity: 'epic',
    type: 'behaviorMod',
    tags: ['scaling', 'power'],
    apply: (stats: PlayerStats): PlayerStats => stats,
  },
  {
    id: 'vengeance',
    name: 'Vengeance',
    description: 'Deal 200% damage for 5s after taking damage',
    rarity: 'epic',
    type: 'behaviorMod',
    tags: ['damage', 'burst'],
    apply: (stats: PlayerStats): PlayerStats => stats,
  },

  // === LEGENDARY PERKS ===
  {
    id: 'black_hole',
    name: 'Void Singularity',
    description: 'Pull all enemies toward you while dealing damage',
    rarity: 'legendary',
    type: 'weaponAugment',
    tags: ['aoe', 'ultimate'],
    apply: (stats: PlayerStats): PlayerStats => stats,
  },
  {
    id: 'time_freeze',
    name: 'Temporal Stasis',
    description: 'Freeze time for 3s every 30s',
    rarity: 'legendary',
    type: 'behaviorMod',
    tags: ['utility', 'ultimate'],
    apply: (stats: PlayerStats): PlayerStats => stats,
  },
  {
    id: 'sword_master',
    name: 'Blade Storm',
    description: 'Summon 12 spinning swords around you',
    rarity: 'legendary',
    type: 'weaponAugment',
    tags: ['aoe', 'ultimate'],
    apply: (stats: PlayerStats): PlayerStats => stats,
  },
  {
    id: 'immortal',
    name: 'Immortal Spirit',
    description: 'Become invincible for 10s after revival',
    rarity: 'legendary',
    type: 'behaviorMod',
    tags: ['survival', 'ultimate'],
    apply: (stats: PlayerStats): PlayerStats => stats,
  },
  {
    id: 'cosmic_arrow',
    name: 'Cosmic Arrow',
    description: 'Every 10th shot creates a universe-destroying explosion',
    rarity: 'legendary',
    type: 'weaponAugment',
    tags: ['damage', 'ultimate'],
    apply: (stats: PlayerStats): PlayerStats => ({
      ...stats,
      damage: stats.damage * 1.2,
    }),
  },
];
